name: Deploy contracts and update Vercel environment variables

on:
  push:
    branches:
      - staging
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging

    steps:
    - name: checkout project
      uses: actions/checkout@v3

    - name: use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: install dependencies
      run: npm install

    - name: Configurer le fichier .env
      run: node scripts/createEnvFile.js
      env:
        SONIC_PRIVATE_KEY: ${{ secrets.SONIC_PRIVATE_KEY }}
        SONIC_TESTNET_URL: "https://rpc.sonic.fantom.network/"
        LOCALHOST_PRIVATE_KEY: ${{ secrets.LOCALHOST_PRIVATE_KEY }}
        DAPP_URL: ${{ vars.DAPP_URL }}
        VERCEL_AUTOMATION_BYPASS_SECRET: ${{ secrets.VERCEL_AUTOMATION_BYPASS_SECRET }}

    - name: execute deploy script
      id: deploy_script
      run: |
        npx hardhat run scripts/deploy_and_create_world.ts --network sonicTestnet 2>&1 | tee script_output.txt

    - name: extract addresses 
      id: extract_addresses
      run: |
        GAME_ADDRESS=$(grep "NEXT_PUBLIC_GAME_ADDRESS=" script_output.txt | awk -F= '{print $2}')
        WORLD_ADDRESS=$(grep "NEXT_PUBLIC_WORLD_ADDRESS=" script_output.txt | awk -F= '{print $2}')
        HERO_ADDRESS=$(grep "NEXT_PUBLIC_HERO_ADDRESS=" script_output.txt | awk -F= '{print $2}')
        HEROENCOUNTERS_ADDRESS=$(grep "NEXT_PUBLIC_HEROENCOUNTERS_ADDRESS=" script_output.txt | awk -F= '{print $2}')
        HEROCLASSES_ADDRESS=$(grep "NEXT_PUBLIC_HEROCLASSES_ADDRESS=" script_output.txt | awk -F= '{print $2}')
        MONSTERS_ADDRESS=$(grep "NEXT_PUBLIC_MONSTERS_ADDRESS=" script_output.txt | awk -F= '{print $2}')
        HERO_INVENTORIES_ADDRESS=$(grep "NEXT_PUBLIC_HERO_INVENTORIES_ADDRESS=" script_output.txt | awk -F= '{print $2}')

        echo "GAME_ADDRESS=$GAME_ADDRESS" >> $GITHUB_ENV
        echo "WORLD_ADDRESS=$WORLD_ADDRESS" >> $GITHUB_ENV
        echo "HERO_ADDRESS=$HERO_ADDRESS" >> $GITHUB_ENV
        echo "HEROENCOUNTERS_ADDRESS=$HEROENCOUNTERS_ADDRESS" >> $GITHUB_ENV
        echo "HEROCLASSES_ADDRESS=$HEROCLASSES_ADDRESS" >> $GITHUB_ENV
        echo "MONSTERS_ADDRESS=$MONSTERS_ADDRESS" >> $GITHUB_ENV
        echo "HERO_INVENTORIES_ADDRESS=$HERO_INVENTORIES_ADDRESS" >> $GITHUB_ENV

    - name: update env variables on Vercel
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        GAME_ADDRESS: ${{ env.GAME_ADDRESS }}
        WORLD_ADDRESS: ${{ env.WORLD_ADDRESS }}
        HERO_ADDRESS: ${{ env.HERO_ADDRESS }}
        HEROENCOUNTERS_ADDRESS: ${{ env.HEROENCOUNTERS_ADDRESS }}
        HEROCLASSES_ADDRESS: ${{ env.HEROCLASSES_ADDRESS }}
        MONSTERS_ADDRESS: ${{ env.MONSTERS_ADDRESS }}
        HERO_INVENTORIES_ADDRESS: ${{ env.HERO_INVENTORIES_ADDRESS }}
      run: |
        #!/usr/bin/env bash

        # Fonction pour supprimer un secret sur Vercel
        delete_secret() {
          local name=$1

          # Récupérer l'ID du secret existant
          RESPONSE=$(curl -s -G "https://api.vercel.com/v2/secrets" \
            -H "Authorization: Bearer $VERCEL_TOKEN" \
            --data-urlencode "teamId=$VERCEL_TEAM_ID")

          SECRET_ID=$(echo "$RESPONSE" | jq -r --arg name "$name" '.secrets[] | select(.name==$name) | .uid')

          if [ -n "$SECRET_ID" ]; then
            # Supprimer le secret existant
            curl -s -X DELETE "https://api.vercel.com/v2/secrets/$SECRET_ID?teamId=$VERCEL_TEAM_ID" \
              -H "Authorization: Bearer $VERCEL_TOKEN"
            echo "Deleted existing secret $name"
          else
            echo "Secret $name not found, no deletion performed."
          fi
        }

        # Fonction pour créer un secret sur Vercel
        create_secret() {
          local name=$1
          local value=$2

          curl -s -X POST "https://api.vercel.com/v2/secrets?teamId=$VERCEL_TEAM_ID" \
            -H "Authorization: Bearer $VERCEL_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{
              "name": "'"$name"'",
              "value": "'"$value"'"
            }' > /dev/null
          echo "Created secret $name"
        }

        # Supprimer et recréer les secrets
        delete_secret "NEXT_PUBLIC_GAME_ADDRESS"
        create_secret "NEXT_PUBLIC_GAME_ADDRESS" "$GAME_ADDRESS"

        delete_secret "NEXT_PUBLIC_WORLD_ADDRESS"
        create_secret "NEXT_PUBLIC_WORLD_ADDRESS" "$WORLD_ADDRESS"

        delete_secret "NEXT_PUBLIC_HERO_ADDRESS"
        create_secret "NEXT_PUBLIC_HERO_ADDRESS" "$HERO_ADDRESS"

        delete_secret "NEXT_PUBLIC_HEROENCOUNTERS_ADDRESS"
        create_secret "NEXT_PUBLIC_HEROENCOUNTERS_ADDRESS" "$HEROENCOUNTERS_ADDRESS"

        delete_secret "NEXT_PUBLIC_HEROCLASSES_ADDRESS"
        create_secret "NEXT_PUBLIC_HEROCLASSES_ADDRESS" "$HEROCLASSES_ADDRESS"

        delete_secret "NEXT_PUBLIC_MONSTERS_ADDRESS"
        create_secret "NEXT_PUBLIC_MONSTERS_ADDRESS" "$MONSTERS_ADDRESS"

        delete_secret "NEXT_PUBLIC_HERO_INVENTORIES_ADDRESS"
        create_secret "NEXT_PUBLIC_HERO_INVENTORIES_ADDRESS" "$HERO_INVENTORIES_ADDRESS"
